services:
  - type: web
    name: live-polling-api
    runtime: docker
    plan: starter
    region: oregon
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /api/health
    numInstances: 1
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 80

databases:
  - name: live-polling-redis
    plan: starter
    type: redis
    region: oregon
    maxmemoryPolicy: allkeys-lru
