services:
  - type: web
    name: live-polling-api
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
    healthCheckPath: /api/health
