import express from "express";
import dotenv from "dotenv";
import cors from "cors";
import { createServer } from "http";
import { Server } from "socket.io";
import prisma from "./config/database";
import historyRoutes from "./routes/historyRoutes";
import { setupSocketHandlers } from "./sockets/index";

// Load environment variables
dotenv.config();

const app = express();
const server = createServer(app);
const io = new Server(server, {
  cors: {
    origin: process.env.CORS_ORIGIN || "http://localhost:5173",
    methods: ["GET", "POST"],
  },
});
const PORT = parseInt(process.env.PORT || "3001", 10);
const HOST = process.env.HOST || "0.0.0.0";

// Middlewares
app.use(
  cors({
    origin: process.env.CORS_ORIGIN || "http://localhost:5173",
    credentials: true,
  })
);
app.use(express.json());

// API Routes (Only essential ones)
app.use("/api/history", historyRoutes);

// Routes
app.get("/", (req, res) => {
  res.json({ message: "Hello from Live Polling API!" });
});

app.get("/api/health", async (req, res) => {
  try {
    // Test database connection
    await prisma.$queryRaw`SELECT 1`;
    res.json({
      status: "OK",
      database: "Connected",
      timestamp: new Date().toISOString(),
    });
  } catch (error) {
    res.status(500).json({
      status: "ERROR",
      database: "Disconnected",
      error: error instanceof Error ? error.message : "Unknown error",
    });
  }
});

// Test database operations
app.get("/api/test-db", async (req, res) => {
  try {
    const pollCount = await prisma.pollHistory.count();
    res.json({
      message: "Database connection successful",
      pollHistoryCount: pollCount,
    });
  } catch (error) {
    res.status(500).json({
      error: "Database connection failed",
      details: error instanceof Error ? error.message : "Unknown error",
    });
  }
});

// Setup Socket.io (Main communication method)
setupSocketHandlers(io);

// Start server
server.listen(PORT, HOST, () => {
  console.log(`🚀 Server running on ${HOST}:${PORT}`);
  console.log(`📊 Live Polling API is ready!`);
  console.log(`🔌 WebSocket communication enabled`);
  console.log(
    `🗄️ Database: ${process.env.DATABASE_URL ? "Configured" : "Not configured"}`
  );
});

// Generated by Copilot

// Graceful shutdown
process.on("SIGINT", async () => {
  console.log("Shutting down gracefully...");
  await prisma.$disconnect();
  process.exit(0);
});

process.on("SIGTERM", async () => {
  console.log("Shutting down gracefully...");
  await prisma.$disconnect();
  process.exit(0);
});

export default app;
